var CC;var check_cookie_show=1;window.onload=function(){$(window).scroll(function(){if($(this).scrollTop()){$('#back-to-top').fadeIn();}else{$('#back-to-top').fadeOut();}});$("#back-to-top").click(function(){$("html, body").animate({scrollTop:0},100);});$("#txt-search").on('click',function(e){$(".overlay").show();$(".list-cate-ajax").hide();$("#chevron").css({'transform':"rotate(0)"});$(this).data('status','off');})
$(".overlay").on('click',function(){$(this).hide();$("#list-suggest").html('');});$("#show-menu").on('click',function(e){$(".mobile-menu").css({left:0});$(".overlay-full").show();e.stopPropagation();});$(".close-mobile").on('click',function(){$(".mobile-menu").css({left:"-300px"});$(".overlay-full").hide();})
$(".overlay-full").on('click',function(){$(".mobile-menu").css({left:"-300px"});$(this).hide();})
$("#expand").on('click',function(){$("#iframehtml5").addClass("force_full_screen");$("#_exit_full_screen").removeClass('hidden');requestFullScreen(document.body);});$("#_exit_full_screen").on('click',cancelFullScreen);$('input[name="keywords"]').on('keyup',async function(e){let value=$(this).val();let url="/query.ajax"
if(value.length==0){$("#list-suggest").html('');return;}
$.ajax({type:"POST",url:url,data:{q:value},success:function(data){let parser_data=JSON.parse(data);$("#list-suggest").html(parser_data);}});return;});add_plugin();CC=new GMCookie();if(!CC.getPermision()){let now=new Date().getTime()/1000;let last_popup=localStorage.getItem('cookie_time');if(!last_popup){localStorage.setItem('cookie_time',now);$(".cookie-setting").show();}else{if(now-last_popup>300){localStorage.setItem('cookie_time',now);$(".cookie-setting").show();}}}else{let data_cookie=CC.read();if(data_cookie&&data_cookie.length>2){check_cookie_show=0;$("#recent-game").css({display:"flex"});$("#recent-game-mobile").css({display:"flex"});if(window.location.pathname.indexOf("recent")>-1){CC.render(null,false);}}}}
function recentGame(event){event.preventDefault();try{CC.render();$(".mobile-menu").css({left:"-300px"});$(".overlay-full").hide();return;}catch(e){return;}}
function cookiePermission(value){if(value){CC.accpet();}else{CC.reject();}
$(".cookie-setting").hide();}
function add_plugin(){let url="/add-plugin.ajax";if(typeof id_game!='undefined'&&typeof url_game!='undefined'){$.ajax({type:"POST",url:url,data:{id:id_game,url:url_game},success:function(data){if(data){let html=JSON.parse(data);if(html.html_rate){$("#append-rate").html(html.html_rate);}
if(html.html_comment){$("#append-comment").html(html.html_comment);}}}});}}
function paging(p){$(".gif").removeClass("hidden");let url='/paging.ajax';let current_url=location.origin+location.pathname;$.ajax({type:"POST",url:url,data:{page:p,keywords:keywords,tag_id:tag_id,category_id:category_id,field_order:field_order,order_type:order_type,is_hot:is_hot,is_new:is_new,limit:limit},success:function(xxxx){$(".gif").addClass("hidden");$("html, body").animate({scrollTop:0},0);if(xxxx!==''){let data=JSON.parse(xxxx);$("#ajax-append").html(data.content);}}});}
function scrollToDiv(element){if($(element).length){$('html,body').animate({scrollTop:$(element).offset().top-100});}}
function closeBox(){$(".close-sharing-box").hide();$(".clipboard-share").addClass("hide-zindex");}
function showSharingBox(){$(".close-sharing-box").show();$(".clipboard-share").removeClass("hide-zindex");}
function expand(){$("#expand").on('click',function(){$("#_exit_full_screen").removeClass('hidden');$("#iframehtml5").addClass("force_full_screen");requestFullScreen(document.body);});$("#_exit_full_screen").on('click',cancelFullScreen);$(".site-sort").on('click',function(){$(".site-sort").removeClass("active");$(this).addClass("active");let data_sort=$(this).data('sort');field_order=data_sort;paging(1);});}
function clickLink(event,slug,type,flag=true){event.preventDefault();try{callLink(slug,type);return true;}catch(e){return true;}}
function callLink(slug,type,obj=null,flag=true){$(".layer-loading").removeClass('hidden');let url='/load_game_home.ajax';if(type=='footermenu'){url='/load_footer_ajax.ajax';}
$.ajax({url:url,type:"POST",data:{slug:slug,type:type,object_data:obj},success:function(data,textStatus,jqXHR){$("html, body").animate({scrollTop:0},0);$(".layer-loading").addClass('hidden');if(data){let data_html=JSON.parse(data);$("#game-page").html(data_html.content);changeMetaTag(data_html.metadata,flag);if(slug=="contact-us"){runValidate();}
expand();$(".mobile-menu").css({left:"-300px"});$(".overlay-full").hide();}}})}
function changeMetaTag(meta_object,flag=true){if(typeof meta_object!='object')
return;$('title').html(meta_object.site_title);$('meta[name="title"]').attr("content",meta_object.site_title);$('meta[name="description"]').attr("content",meta_object.site_description);$('meta[name="keywords"]').attr("content",meta_object.site_keywords);$('meta[name="news_keywords"]').attr("content",meta_object.site_keywords);$('link[rel="canonical"]').attr("href",meta_object.base_url);$('meta[property="og:title"]').attr("content",meta_object.site_title);$('meta[property="og:url"]').attr("content",meta_object.base_url);$('meta[property="og:description"]').attr("content",meta_object.site_description);$('meta[property="og:site_name"]').attr("content",meta_object.site_title);$('meta[name="twitter:title"]').attr("content",meta_object.site_title);$('meta[name="twitter:url"]').attr("content",meta_object.base_url);$('meta[name="twitter:description"]').attr("content",meta_object.site_description);let url_push=meta_object.base_url.replace(location.origin,"");if(!url_push){url_push="/";}
if(typeof(ga)=='function'){ga('set','page',url_push);ga('send','pageview');}
if(flag)
history.pushState(null,'',meta_object.base_url);}
function runValidate(){jQuery("#contact-form").validate({focusInvalid:false,onfocusout:false,ignore:".ignore",errorElement:"div",errorPlacement:function(error,element){error.appendTo("div#contact_err");},rules:{Name:{required:true,maxlength:255,},Email:{required:true,email:true,maxlength:100},Website:{required:false,maxlength:255,},Topic:{required:false,maxlength:255,},Message:{required:true,maxlength:65525},"contactChecked":{required:true}},messages:{Name:{required:"Please type your name!",maxlength:"255"},Email:{required:"Please type your email!",email:"Please check a valid email!",maxlength:"100"},Message:{required:"Please type your message!",maxlength:"65525"},"contactChecked":{required:"Please agree to the terms and conditions before comment."}},submitHandler:function(){let question_ajax="/make-contact.ajax";let name=jQuery("#Name").val();let email=jQuery("#Email").val();let website=jQuery("#Website").val();let subject=jQuery("#Topic").val();let message=jQuery("#Message").val();let metadataload={};metadataload.name=name;metadataload.email=email;metadataload.website=website;metadataload.subject=subject;metadataload.message=message;jQuery.ajax({url:question_ajax,data:metadataload,type:'POST',success:function(data){if(data!=0||data!='0'){showSuccessMessage();}}});}});}
function showSuccessMessage(message){document.getElementById('fcf-status').innerHTML='';document.getElementById('fcf-form').style.display='none';document.getElementById('fcf-thank-you').style.display='block';}
function resetFormDemo(){document.getElementById('fcf-form').style.display="block";document.getElementById('fcf-thank-you').style.display="none";}
function requestFullScreen(element){$("#iframehtml5").removeClass("force_half_full_screen");$(".header-game").removeClass("header_game_enable_half_full_screen");var requestMethod=element.requestFullScreen||element.webkitRequestFullScreen||element.mozRequestFullScreen||element.msRequestFullScreen;if(requestMethod){requestMethod.call(element);}else if(typeof window.ActiveXObject!=="undefined"){var wscript=new ActiveXObject("WScript.Shell");if(wscript!==null){wscript.SendKeys("{F11}");}}}
function cancelFullScreen(){$("#_exit_full_screen").addClass('hidden');$("#iframehtml5").removeClass("force_full_screen");$("#iframehtml5").removeClass("force_half_full_screen");$(".header-game").removeClass("header_game_enable_half_full_screen");document.body.style.overflow="unset";var requestMethod=document.cancelFullScreen||document.webkitCancelFullScreen||document.mozCancelFullScreen||document.exitFullScreenBtn;if(requestMethod){requestMethod.call(document);}else if(typeof window.ActiveXObject!=="undefined"){var wscript=new ActiveXObject("WScript.Shell");if(wscript!==null){wscript.SendKeys("{F11}");}}}
if(document.addEventListener){document.addEventListener('webkitfullscreenchange',exitHandler,false);document.addEventListener('mozfullscreenchange',exitHandler,false);document.addEventListener('fullscreenchange',exitHandler,false);document.addEventListener('MSFullscreenChange',exitHandler,false);}
function exitHandler(){if(document.webkitIsFullScreen===false||document.mozFullScreen===false||document.msFullscreenElement===false){cancelFullScreen();}}